# Generated by Django 2.0 on 2022-02-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null=True)),
                ('reciever', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date_tran', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
